/**
 * .../eform-pdf/pdfSections.ts
 *
 * One function per visual section of the e-form PDF, each just drawing
 * onto the jsPDF doc it's given and returning the y-coordinate to
 * continue from — buildEFormPdf.ts calls these in order. Kept separate
 * from buildEFormPdf.ts so each section reads and edits independently
 * (e.g. tweaking the footer text doesn't mean re-reading the whole
 * layout function).
 */

import type { jsPDF } from "jspdf"
import { PDF_COLORS, PDF_PAGE } from "./pdfTheme"

export interface EFormData {
  electionName: string
  officeName: string
  fullName: string
  phone: string
  reference: string
  paymentDate: string // already formatted for display
  editExpiresLabel: string // already formatted, or "No further edits allowed"
}

export function drawHeader(doc: jsPDF, y: number): number {
  const { marginMm, widthMm } = PDF_PAGE

  doc.setFillColor(...PDF_COLORS.brass)
  doc.rect(0, 0, widthMm, 38, "F")

  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(20)
  doc.text("Spotix Elections", marginMm, 20)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(11)
  doc.text("Candidate e-Form", marginMm, 29)

  return 52
}

export function drawTitle(doc: jsPDF, y: number, data: EFormData): number {
  const { marginMm } = PDF_PAGE

  doc.setTextColor(...PDF_COLORS.ink)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.text(data.electionName, marginMm, y)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(12)
  doc.setTextColor(...PDF_COLORS.brass)
  doc.text(`Contesting: ${data.officeName}`, marginMm, y + 8)

  return y + 20
}

/** Draws the candidate photo (if we got one as a data URL) in a rounded-ish square, or a neutral placeholder box if not. */
export function drawPhoto(doc: jsPDF, y: number, photoDataUrl: string | null): number {
  const { widthMm, marginMm } = PDF_PAGE
  const size = 32
  const x = widthMm - marginMm - size

  doc.setDrawColor(...PDF_COLORS.line)
  doc.setLineWidth(0.4)

  if (photoDataUrl) {
    try {
      doc.addImage(photoDataUrl, "JPEG", x, y, size, size, undefined, "FAST")
      doc.rect(x, y, size, size) // thin outline over the image
    } catch {
      drawPhotoPlaceholder(doc, x, y, size)
    }
  } else {
    drawPhotoPlaceholder(doc, x, y, size)
  }

  return y
}

function drawPhotoPlaceholder(doc: jsPDF, x: number, y: number, size: number) {
  doc.setFillColor(...PDF_COLORS.line)
  doc.rect(x, y, size, size, "F")
  doc.setTextColor(...PDF_COLORS.muted)
  doc.setFontSize(8)
  doc.text("No photo", x + size / 2, y + size / 2, { align: "center" })
}

export function drawDetailsTable(doc: jsPDF, y: number, data: EFormData): number {
  const { marginMm, widthMm } = PDF_PAGE
  const rows: [string, string][] = [
    ["Candidate", data.fullName],
    ["Phone number", data.phone || "—"],
    ["Payment reference", data.reference],
    ["Date paid", data.paymentDate],
    ["Edit window", data.editExpiresLabel],
  ]

  let rowY = y
  doc.setFontSize(10.5)
  for (const [label, value] of rows) {
    doc.setDrawColor(...PDF_COLORS.line)
    doc.setLineWidth(0.2)
    doc.line(marginMm, rowY + 6, widthMm - marginMm, rowY + 6)

    doc.setFont("helvetica", "normal")
    doc.setTextColor(...PDF_COLORS.muted)
    doc.text(label, marginMm, rowY + 3)

    doc.setFont("helvetica", "bold")
    doc.setTextColor(...PDF_COLORS.ink)
    doc.text(value, widthMm - marginMm, rowY + 3, { align: "right" })

    rowY += 12
  }

  return rowY + 6
}

export function drawConfirmedBadge(doc: jsPDF, y: number): number {
  const { marginMm } = PDF_PAGE
  doc.setFillColor(...PDF_COLORS.success)
  doc.roundedRect(marginMm, y, 46, 9, 2, 2, "F")
  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.text("✓ PAYMENT CONFIRMED", marginMm + 23, y + 6, { align: "center" })
  return y + 18
}

export function drawFooter(doc: jsPDF): void {
  const { marginMm, widthMm, heightMm } = PDF_PAGE
  const footerY = heightMm - 34

  doc.setDrawColor(...PDF_COLORS.line)
  doc.setLineWidth(0.3)
  doc.line(marginMm, footerY, widthMm - marginMm, footerY)

  doc.setFont("helvetica", "italic")
  doc.setFontSize(11)
  doc.setTextColor(...PDF_COLORS.brass)
  doc.text("Good luck from all of us at Spotix!", marginMm, footerY + 10)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(...PDF_COLORS.muted)
  doc.text("Questions about your form? Reach out to support@spotix.com.ng and we'll help you out.", marginMm, footerY + 18)

  doc.setFontSize(8)
  doc.text("Generated by Spotix Elections — spotix.com.ng", marginMm, heightMm - 10)
}
